{
  "compatibilityLevel": 1600,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"TB_Empresa\",\"TB_NotaFiscal\",\"TB_GProduto\",\"TB_Produto\",\"_Medidas\",\"TB_Cliente\",\"Atualização\",\"_Senhas\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "TB_Dimensao"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ],
        "folder": "TB_Fatos"
      }
    ],
    "relationships": [
      {
        "name": "fb360d80-41fa-07a7-9a03-b244493473a0",
        "fromColumn": "PRD_GPR_IdGrupoProduto",
        "fromTable": "TB_Produto",
        "toColumn": "GRP_Codigo",
        "toTable": "TB_GProduto"
      },
      {
        "name": "d2bfe013-8e68-895a-fb9d-8872fdf9d669",
        "fromColumn": "NFI_PRD_IdProduto",
        "fromTable": "TB_NotaFiscal",
        "toColumn": "PRD_Id",
        "toTable": "TB_Produto"
      },
      {
        "name": "2ae8069f-772a-1131-9b66-b765742b6aed",
        "fromColumn": "NTF_CLI_IdCliente",
        "fromTable": "TB_NotaFiscal",
        "toColumn": "CLI_Codigo",
        "toTable": "TB_Cliente"
      },
      {
        "name": "f890df60-94db-7507-cb18-688338f20803",
        "fromColumn": "CLI_EMP_IdEmpresa",
        "fromTable": "TB_Cliente",
        "toColumn": "EMP_Id",
        "toTable": "TB_Empresa"
      },
      {
        "name": "40309711-f238-4c85-92df-3003ed3eb0a6",
        "fromColumn": "data atualizada",
        "fromTable": "Atualização",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c04fdd3a-08b1-4ddd-9343-ae9b9ec29a13"
      },
      {
        "name": "f3b7e5c1-20b6-4690-a889-117c88c86a88",
        "fromColumn": "Date",
        "fromTable": "CALENDARIO DAX",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2ca12eb1-9712-4962-a2da-3915b11f5664"
      },
      {
        "name": "18ef16f5-5bc4-a9df-5c99-e937715fbe7e",
        "fromColumn": "NTF_DataEmissao",
        "fromTable": "TB_NotaFiscal",
        "toColumn": "Date",
        "toTable": "CALENDARIO DAX"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "TB_Empresa",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "EMP_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ab78934d-93e3-4e12-a8a6-7e071c2e09f1",
            "sourceColumn": "EMP_Id",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_NomeFantasia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0620e37-7c73-404f-929a-0f1548fd63ea",
            "sourceColumn": "EMP_NomeFantasia",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_RazaoSocial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b630d73b-ddf2-4b19-a41e-36daa8f6db8e",
            "sourceColumn": "EMP_RazaoSocial",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_CNPJ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13f73c02-1ca0-4c5a-bc37-136a5f28ef05",
            "sourceColumn": "EMP_CNPJ",
            "summarizeBy": "none"
          },
          {
            "name": "EMP_InscricaoEstadual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f60bec6e-a1e0-4f79-9f99-e9f881c37205",
            "sourceColumn": "EMP_InscricaoEstadual",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6dfe2404-27ab-4949-bbba-98f2e9cda574",
        "partitions": [
          {
            "name": "TB_Empresa",
            "mode": "import",
            "queryGroup": "TB_Dimensao",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\" = Workspaces{[workspaceId=\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"]}[Data],",
                "    #\"bda523c5-15d7-4d7e-890a-25ae41b17802\" = #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"{[dataflowId=\"bda523c5-15d7-4d7e-890a-25ae41b17802\"]}[Data],",
                "    TB_Empresa_ = #\"bda523c5-15d7-4d7e-890a-25ae41b17802\"{[entity=\"TB_Empresa\",version=\"\"]}[Data]",
                "in",
                "    TB_Empresa_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TB_NotaFiscal",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "NFI_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f640059-3f00-4d3e-b968-a185787d4c74",
            "sourceColumn": "NFI_Id",
            "summarizeBy": "count"
          },
          {
            "name": "NFI_NTF_IdNotaFiscal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8e9d285-f4c9-4907-9ff7-09b7459f55b8",
            "sourceColumn": "NFI_NTF_IdNotaFiscal",
            "summarizeBy": "sum"
          },
          {
            "name": "NFI_PRD_IdProduto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0617228c-557c-4fa8-9857-a6ae1e8170b7",
            "sourceColumn": "NFI_PRD_IdProduto",
            "summarizeBy": "none"
          },
          {
            "name": "NFI_Quantidade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "935ffc8e-5fa6-40b4-ae10-9af84b2b6a3a",
            "sourceColumn": "NFI_Quantidade",
            "summarizeBy": "sum"
          },
          {
            "name": "NFI_ValorTabelado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e3701866-5314-4a6c-9434-96eca168bed1",
            "sourceColumn": "NFI_ValorTabelado",
            "summarizeBy": "sum"
          },
          {
            "name": "NFI_ValorDesconto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "641ac1d7-3b68-4fd8-a015-d08a831ea917",
            "sourceColumn": "NFI_ValorDesconto",
            "summarizeBy": "sum"
          },
          {
            "name": "NFI_ValorTotal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ee555e4a-2107-432e-95fa-258e3093cf0f",
            "sourceColumn": "NFI_ValorTotal",
            "summarizeBy": "sum"
          },
          {
            "name": "NFI_CFO_IdCFOP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "93e97953-f401-4e6a-8392-cbc8c70125b0",
            "sourceColumn": "NFI_CFO_IdCFOP",
            "summarizeBy": "none"
          },
          {
            "name": "NFI_ValorCusto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bcfd809d-8ac4-4d45-9a55-5d09126882f2",
            "sourceColumn": "NFI_ValorCusto",
            "summarizeBy": "sum"
          },
          {
            "name": "NTF_Numero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca2b4e11-98fe-4028-8ee9-8b18d8c20f21",
            "sourceColumn": "NTF_Numero",
            "summarizeBy": "none"
          },
          {
            "name": "NTF_Serie",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca92c3cf-a3c0-473c-a309-0c3b022d5932",
            "sourceColumn": "NTF_Serie",
            "summarizeBy": "none"
          },
          {
            "name": "NTF_DataEmissao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "5f9d5f72-eca8-46f1-9145-9da9e0c1ab38",
            "sourceColumn": "NTF_DataEmissao",
            "summarizeBy": "none"
          },
          {
            "name": "NTF_ValorTotalNota",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68f66c76-5ece-48e4-9ba0-49d1c12cee1b",
            "sourceColumn": "NTF_ValorTotalNota",
            "summarizeBy": "sum"
          },
          {
            "name": "NTF_TipoDocumento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9c7e44da-b716-4da9-8f93-dc765a4dab21",
            "sourceColumn": "NTF_TipoDocumento",
            "summarizeBy": "none"
          },
          {
            "name": "NTF_NaturezaOperacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f97de82b-248b-462c-8a7c-a8828fd2382c",
            "sourceColumn": "NTF_NaturezaOperacao",
            "summarizeBy": "none"
          },
          {
            "name": "NFI_Cancelada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "073a6ce3-756f-44aa-a8bb-36beb389c639",
            "sourceColumn": "NFI_Cancelada",
            "summarizeBy": "none"
          },
          {
            "name": "NTF_Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c056aedb-ef8a-4f46-898b-112ec2858ede",
            "sourceColumn": "NTF_Codigo",
            "summarizeBy": "sum"
          },
          {
            "name": "NTF_FOR_IdFornecedor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "881d7305-c895-4174-9545-d8b4663fe9b2",
            "sourceColumn": "NTF_FOR_IdFornecedor",
            "summarizeBy": "sum"
          },
          {
            "name": "NTF_CLI_IdCliente",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a0844ba5-7a24-4902-a91e-5de72cf61aea",
            "sourceColumn": "NTF_CLI_IdCliente",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4d5dda3f-547c-4ca0-a284-0f2c8d665df6",
        "partitions": [
          {
            "name": "TB_NotaFiscal",
            "mode": "import",
            "queryGroup": "TB_Fatos",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\" = Workspaces{[workspaceId=\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"]}[Data],",
                "    #\"bda523c5-15d7-4d7e-890a-25ae41b17802\" = #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"{[dataflowId=\"bda523c5-15d7-4d7e-890a-25ae41b17802\"]}[Data],",
                "    TB_NotaFiscal_ = #\"bda523c5-15d7-4d7e-890a-25ae41b17802\"{[entity=\"TB_NotaFiscal\",version=\"\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(TB_NotaFiscal_,{{\"NTF_DataEmissao\", type date}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TB_GProduto",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "GRP_Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ac198eab-19c4-48b5-862a-d03878b54733",
            "sourceColumn": "GRP_Codigo",
            "summarizeBy": "none"
          },
          {
            "name": "GRP_Descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "982741ec-6a6d-4ccf-a5bc-c211e39e0523",
            "sourceColumn": "GRP_Descricao",
            "summarizeBy": "none"
          },
          {
            "name": "GRP_CodigoProdutoInicial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "151bfd55-51cf-46a1-9aa8-00a7cb42caa8",
            "sourceColumn": "GRP_CodigoProdutoInicial",
            "summarizeBy": "none"
          },
          {
            "name": "GRP_CodigoProdutoFinal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f0ceb7c-1096-4eb7-81d2-868cce4a1d67",
            "sourceColumn": "GRP_CodigoProdutoFinal",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fc5ec8fd-aee5-4f29-a0d0-f8d22bb73d4b",
        "partitions": [
          {
            "name": "TB_GProduto",
            "mode": "import",
            "queryGroup": "TB_Dimensao",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\" = Workspaces{[workspaceId=\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"]}[Data],",
                "    #\"bda523c5-15d7-4d7e-890a-25ae41b17802\" = #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"{[dataflowId=\"bda523c5-15d7-4d7e-890a-25ae41b17802\"]}[Data],",
                "    TB_GProduto_ = #\"bda523c5-15d7-4d7e-890a-25ae41b17802\"{[entity=\"TB_GProduto\",version=\"\"]}[Data]",
                "in",
                "    TB_GProduto_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "TB_Produto",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PRD_Id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2a3e62ff-f846-48fb-be30-134f9a5f0e89",
            "sourceColumn": "PRD_Id",
            "summarizeBy": "none"
          },
          {
            "name": "PRD_Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a64fe9c-23dc-4fcf-986d-a69be0bd3e4c",
            "sourceColumn": "PRD_Codigo",
            "summarizeBy": "none"
          },
          {
            "name": "PRD_GPR_IdGrupoProduto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aea36f04-f4d2-4500-b5bb-86a4fb991332",
            "sourceColumn": "PRD_GPR_IdGrupoProduto",
            "summarizeBy": "none"
          },
          {
            "name": "PRD_UNP_IdUnidadeProduto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "909c37d5-784d-4664-a69b-61c5ef64f2d8",
            "sourceColumn": "PRD_UNP_IdUnidadeProduto",
            "summarizeBy": "sum"
          },
          {
            "name": "PRD_Descricao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dcdf4b5-de10-4339-bbce-3851af2d94f1",
            "sourceColumn": "PRD_Descricao",
            "summarizeBy": "none"
          },
          {
            "name": "PRD_Ativo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6553ff94-6af9-4fba-b012-54cce56fcfd7",
            "sourceColumn": "PRD_Ativo",
            "summarizeBy": "none"
          },
          {
            "name": "UNP_Sigla",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bdb491d-1fd4-425c-892f-c009146833f8",
            "sourceColumn": "UNP_Sigla",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "46dd8f1d-f76f-4d12-bae9-0217d23efbfc",
        "partitions": [
          {
            "name": "TB_Produto",
            "mode": "import",
            "queryGroup": "TB_Dimensao",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\" = Workspaces{[workspaceId=\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"]}[Data],",
                "    #\"bda523c5-15d7-4d7e-890a-25ae41b17802\" = #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"{[dataflowId=\"bda523c5-15d7-4d7e-890a-25ae41b17802\"]}[Data],",
                "    TB_Produto_ = #\"bda523c5-15d7-4d7e-890a-25ae41b17802\"{[entity=\"TB_Produto\",version=\"\"]}[Data]",
                "in",
                "    TB_Produto_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Medidas",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "e1045235-e3c8-416c-b155-523e55311d50",
        "measures": [
          {
            "name": "01. Total Faturamento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "01. Faturamento\\Totais",
            "expression": [
              "",
              "// Soma total de Faturamento com Desconto",
              "SUMX(",
              "    TB_NotaFiscal,",
              "    TB_NotaFiscal[NFI_ValorTotal] - TB_NotaFiscal[NFI_ValorDesconto] )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "97ad3d4f-39bb-4b44-9caa-04838c809388"
          },
          {
            "name": "01. Qtd Vendas",
            "displayFolder": "01. Faturamento\\Totais",
            "expression": [
              "",
              "// Mostra a quantidade de notas vendidas",
              "DISTINCTCOUNT( TB_NotaFiscal[NTF_Codigo] )"
            ],
            "formatString": "#,0",
            "lineageTag": "7cd002c3-416f-4da7-8d41-f9f5d8e0c3a4"
          },
          {
            "name": "01. Tickt Medio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "01. Faturamento\\Totais",
            "expression": [
              "",
              "// faturamento / quiantidade de notas",
              "DIVIDE( [01. Total Faturamento], [01. Qtd Vendas], 0 )"
            ],
            "lineageTag": "f70eb5b8-2598-4cdb-8e83-5aefcc620fc7"
          },
          {
            "name": "01. Descontos",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "01. Faturamento\\Totais",
            "expression": [
              "",
              "// Mostra o total de descontos cedidos",
              "SUM( TB_NotaFiscal[NFI_ValorDesconto] )"
            ],
            "lineageTag": "53739b46-8493-4ea4-aeac-1c23f688f604"
          },
          {
            "name": "02. Quantidade/Volume",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "02. Volume\\Totais",
            "expression": [
              "",
              "// Volume Vendidos",
              "SUM( TB_NotaFiscal[NFI_Quantidade] )"
            ],
            "formatString": "#,0",
            "lineageTag": "17d16c1b-79da-488b-8cda-d41a833ebdc2"
          },
          {
            "name": "01. Fat Ano Anterior",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "01. Faturamento\\Totais",
            "expression": [
              "",
              "// faturamento do Ano anterior( comparação )",
              "CALCULATE(",
              "    [01. Total Faturamento],",
              "    SAMEPERIODLASTYEAR( 'CALENDARIO DAX'[Date] )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "f6c196e1-595e-447c-88e7-892b24d189f3"
          },
          {
            "name": "01. YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "01. Faturamento\\YTD",
            "expression": [
              "",
              "// Year to Date",
              "IF(",
              "    ISBLANK( [01. Total Faturamento] ), BLANK() ,",
              "TOTALYTD(",
              "    [01. Total Faturamento],",
              "    'CALENDARIO DAX'[Date] )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "72e13f21-e45d-43de-958d-c8846db6fcea"
          },
          {
            "name": "01. % vs Ano Ant",
            "displayFolder": "01. Faturamento\\%",
            "expression": [
              "",
              "// % versus ano anterior",
              "DIVIDE( [01. Total Faturamento], [01. Fat Ano Anterior], 0 )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "4028c4ef-83f0-462b-a315-399b5a090145"
          },
          {
            "name": "01. Preco Medio",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "01. Faturamento\\Totais",
            "expression": [
              "",
              "// Preco medio consite em faturamento / volume",
              "DIVIDE( [01. Total Faturamento], [02. Quantidade/Volume] , 0 )"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "d76bb4bb-aca3-4f8b-b984-42c6f521ca29"
          },
          {
            "name": "02. % vs Ano Ant",
            "displayFolder": "02. Volume\\%",
            "expression": [
              "",
              "// Volume vs Ano anterior",
              "DIVIDE( [02. Quantidade/Volume] , [02. Vol Ano Ant], 0 )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "1b63a926-2def-46fa-9195-13361091a0ec"
          },
          {
            "name": "02. Vol Ano Ant",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "02. Volume\\Totais",
            "expression": [
              "",
              "// Volume do Ano anterior",
              "CALCULATE(",
              "    [02. Quantidade/Volume],",
              "    SAMEPERIODLASTYEAR( 'CALENDARIO DAX'[Date] )",
              ")"
            ],
            "lineageTag": "1b30f32e-6f6e-4d2d-b40f-b08502302b0a"
          },
          {
            "name": "Eixo 0",
            "expression": [
              "",
              "// traz o eixo 0 para colocar no grafico o % de Diferença",
              "0"
            ],
            "formatString": "0",
            "lineageTag": "76201000-9881-4ac7-9d6c-d1eef3ef8921"
          },
          {
            "name": "* PeriodoFormatado",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "// Mostra o inicio e final do mes filtrado",
              "VAR DataMin = MIN('CALENDARIO DAX'[Date])",
              "VAR DataMax = MAX('CALENDARIO DAX'[Date])",
              "RETURN ",
              "\"Data: \" & UNICHAR(10) &",
              "FORMAT(DataMin, \"dd mmm yyyy\") &",
              "\" - \" &",
              "FORMAT(DataMax, \"dd mmm yyyy\")"
            ],
            "lineageTag": "7c3e1624-a7e8-4b03-ab50-d7f476692749"
          },
          {
            "name": "* VendaATUAL",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "\"Venda Atual (\" & SELECTEDVALUE( 'CALENDARIO DAX'[Ano-Mes] ) & \" )\""
            ],
            "lineageTag": "89f503ea-caaf-4ae8-a389-e759b7c9f711"
          },
          {
            "name": "* Ultima data Faturamento",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "// mostra qual data teve ultimo fatutamento",
              "FORMAT( MAX( TB_NotaFiscal[NTF_DataEmissao] ), \"dd/mm/yyyy\" )"
            ],
            "lineageTag": "a06e468a-2ecb-4ddf-883a-ddf4813d4957"
          },
          {
            "name": "$ % Tendencia vs Faturamento Ano Ant",
            "expression": [
              "",
              "// Mostra quantos ( % ) esta tendenciando a ficar abaixo do ano anterior",
              "VAR vtend = ",
              "DIVIDE( [01. Tendencia]- [01. Fat Ano Anterior], [01. Fat Ano Anterior], 0 )",
              "VAR _Percent = ",
              "SWITCH(",
              "    TRUE(),",
              "    vtend > 0 , \"⮝\",",
              "    \"⮟\" )",
              "VAR _AB = ",
              "SWITCH(",
              "    TRUE(),",
              "    vtend > 0 , \" Acima\",",
              "    \" Abaixo\" )",
              "RETURN",
              "IF(",
              "    ISBLANK( [01. Total Faturamento] ), BLANK(),",
              "_Percent & FORMAT( vtend, \"Percent\" ) & _AB )"
            ],
            "lineageTag": "7abba8ac-61e1-4345-b532-c35cb6164e3d"
          },
          {
            "name": "01. Tendencia",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "01. Faturamento\\Totais",
            "expression": [
              "",
              "// Mostra como esta tendenciando a fechar o mes caso continue esse faturamento diario",
              "var vTEND = ",
              "DIVIDE([01. Total Faturamento] ,[DIAS_PERCORRIDOS])",
              "RETURN",
              "vTEND * [TOTAL_DIAS]"
            ],
            "lineageTag": "c5e82727-f80d-4b7d-8279-0c759da00bbb"
          },
          {
            "name": "*Calendario Vendas Faturamento",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "var vDia = SELECTEDVALUE('CALENDARIO DAX'[Dia])",
              "",
              "var vTOTAL_Vendas = ",
              "   FORMAT( [01. Total Faturamento] , \"#,00\" )",
              "RETURN",
              "vDia & UNICHAR(10) & vTOTAL_Vendas"
            ],
            "lineageTag": "3afcb1d1-c048-469b-aec8-1d46e8a31b0c"
          },
          {
            "name": "*Format calendario fundo_fat",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "var vDIASEMANA = SELECTEDVALUE('CALENDARIO DAX'[SemanaDIAnum])",
              "var vCHECK = ",
              "SWITCH(",
              "    TRUE(),",
              "    ISBLANK([01. Total Faturamento]),\"blanck\",",
              "    vDIASEMANA IN {1 , 7}, \"#a8a8a8\",\"#d8d8d8\")",
              "RETURN",
              "vCHECK"
            ],
            "lineageTag": "cf7ac118-55e4-4aa0-86d6-3072e38a992c"
          },
          {
            "name": "*Format Calendario_Fat",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "IF(",
              "    ISBLANK([01. Total Faturamento]),\"#a8a8a8\", \"#333333\"",
              "    )"
            ],
            "lineageTag": "00df6e85-6e1b-4427-b8f7-19b57a636caa"
          },
          {
            "name": "*Format Calendario Subtitulo_fat",
            "displayFolder": "Calendario",
            "expression": [
              "",
              "var vMES_ANO = SELECTEDVALUE('CALENDARIO DAX'[Ano-Mes])",
              "RETURN",
              "",
              "\"Total de Faturado em \" & vMES_ANO & \" é de R$ \" & FORMAT([01. Total Faturamento],\"#,0\") & \" || Média por Dia: R$ \" & FORMAT( [01. Media de Faturamento], \"#,0\" )"
            ],
            "lineageTag": "ecf7467d-fb80-4d2b-829c-786abbae830f"
          },
          {
            "name": "01. YTD Ano Ant",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "displayFolder": "01. Faturamento\\YTD",
            "expression": [
              "",
              "// Retorna o year to date do ano anterior",
              "CALCULATE(",
              "    [01. YTD],",
              "    SAMEPERIODLASTYEAR( 'CALENDARIO DAX'[Date] )",
              ")"
            ],
            "formatString": "\"R$\"\\ #,0.00;-\"R$\"\\ #,0.00;\"R$\"\\ #,0.00",
            "lineageTag": "630ea07c-9b7a-408c-b137-ec7321f1fc2a"
          },
          {
            "name": "01. % YTD vs Ano Ant",
            "displayFolder": "01. Faturamento\\%",
            "expression": [
              "",
              "// Mostra o ( % ) vs o ano anterior ",
              "DIVIDE( [01. YTD] , [01. YTD Ano Ant], 0 )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "285b260d-346b-4933-ac81-5d75294ec951"
          },
          {
            "name": "01. Media de Faturamento",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "// calcula a media de faturtamento no mes selecionado",
              "VAR vTABELA = ",
              "AVERAGEX(",
              "    VALUES( 'CALENDARIO DAX'[Dia] ),",
              "    [01. Total Faturamento] )",
              "",
              "RETURN",
              "vTABELA"
            ],
            "lineageTag": "f590004f-c101-4a63-b823-efce8fd030ca"
          },
          {
            "name": "HTML_Filtros_Ativos",
            "expression": [
              "",
              "// Mostra o Botão com Filtros Aplicados",
              "",
              "VAR MinData = MIN('CALENDARIO DAX'[Date])",
              "VAR MaxData = MAX('CALENDARIO DAX'[Date])",
              "",
              "-- Valores selecionados (texto) por filtro",
              "VAR Filtro1  = IF(ISFILTERED('CALENDARIO DAX'[Date]), FORMAT(MinData, \"dd mmm yyyy\") & \" a \" & FORMAT(MaxData, \"dd mmm yyyy\"), BLANK())",
              "VAR Filtro2  = IF(ISFILTERED(TB_Empresa[EMP_NomeFantasia]), CONCATENATEX(VALUES(TB_Empresa[EMP_NomeFantasia]), TB_Empresa[EMP_NomeFantasia], \", \"), BLANK())",
              "VAR Filtro3  = IF(ISFILTERED(TB_GProduto[GRP_Descricao]), CONCATENATEX(VALUES(TB_GProduto[GRP_Descricao]), TB_GProduto[GRP_Descricao], \", \"), BLANK())",
              "VAR Filtro4  = IF(ISFILTERED(TB_Produto[PRD_Descricao]), CONCATENATEX(VALUES(TB_Produto[PRD_Descricao]), TB_Produto[PRD_Descricao], \", \"), BLANK())",
              "",
              "-- Contagem de filtros ativos",
              "VAR TotalFiltros =",
              "    (NOT ISBLANK(Filtro1)) + (NOT ISBLANK(Filtro2)) + (NOT ISBLANK(Filtro3)) +",
              "    (NOT ISBLANK(Filtro4)) ",
              "",
              "VAR Texto =",
              "    IF(TotalFiltros = 1, \"1 ativo\", FORMAT(TotalFiltros, \"0\") & \" ativos\")",
              "",
              "-- Tooltip (caixa) com títulos em negrito",
              "VAR TooltipHTML =",
              "    \"<div style='background:#fff;",
              "            border:1px solid #118DFF;",
              "            border-radius:10px;",
              "            padding:12px 16px;",
              "            font-size:12px;",
              "            color:#333;",
              "            line-height:18px;",
              "            box-shadow:0 2px 6px rgba(0,0,0,0.2);",
              "            width: 1000px;",
              "            max-width:800px;",
              "            max-height:250px;",
              "            overflow-y:auto;'>",
              "        <div style='font-weight:bold; margin-bottom:4px;'>Filtros Aplicados:</div>\" &",
              "        IF(NOT ISBLANK(Filtro1),  \"<div><b>Data:</b> \" & Filtro1 & \"</div>\", \"\") &",
              "        IF(NOT ISBLANK(Filtro2),  \"<div><b>Tipo:</b> \" & Filtro2 & \"</div>\", \"\") &",
              "        IF(NOT ISBLANK(Filtro3),  \"<div><b>Empresa:</b> \" & Filtro3 & \"</div>\", \"\") &",
              "        IF(NOT ISBLANK(Filtro4),  \"<div><b>Grupo Produtos:</b> \" & Filtro4 & \"</div>\", \"\") &",
              "    \"</div>\"",
              "",
              "RETURN",
              "IF(",
              "    TotalFiltros > 0,",
              "    \"<details style='display:inline-block; position:relative;'>",
              "        <summary style='list-style:none; outline:none; cursor:pointer;'>",
              "            <span style='background-color: rgba(17,141,255,0.1);",
              "                         color:#118DFF;",
              "                         border:1px solid #118DFF;",
              "                         border-radius:15px;",
              "                         padding:3px 10px;",
              "                         font-size:8px;",
              "                         font-weight:bold;",
              "                         display:inline-block;'>\" & Texto & \"</span>",
              "        </summary>",
              "    </details>\",",
              "    \"\"",
              ")",
              ""
            ],
            "lineageTag": "c8aedbf4-ca0b-4255-a1cf-c29f6197e94c"
          }
        ],
        "partitions": [
          {
            "name": "_Medidas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#\"Coluna 1\" = _t]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Coluna 1\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Coluna 1\"})",
                "in",
                "    #\"Colunas Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CALENDARIO DAX",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "2b8d423b8188447fbbeb8f66fa41d22d"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "40eeadbb-e618-4b6e-a885-d133521159f7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_2ca12eb1-9712-4962-a2da-3915b11f5664"
                },
                "isDefault": true,
                "relationship": "f3b7e5c1-20b6-4690-a889-117c88c86a88"
              }
            ]
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b8ea9f02-99a7-4e1c-bc2d-6603b2b8d603",
            "sourceColumn": "[Ano]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "AnoNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "f8e470db-4d96-4216-b4d8-f006d7e60ff0",
            "sourceColumn": "[AnoNumber]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "91ede2db-b96b-40fe-be6c-8058e89c730f",
            "sourceColumn": "[Mês]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Nome do Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9e303e7d-1112-4690-9227-a790a36a1069",
            "sourceColumn": "[Nome do Mês]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mês Abrev",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "841e17ab-f758-44df-9af4-659242d626a4",
            "sortByColumn": "Mês",
            "sourceColumn": "[Mês Abrev]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "42011b05-3287-4d25-8b22-87aaec23d6f1",
            "sourceColumn": "[trimestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "semestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "acd101c2-bdf9-4263-b816-791a2aca883e",
            "sourceColumn": "[semestre]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6c055b95-6fe6-4c42-99b4-dc275bf19ed8",
            "sourceColumn": "[Dia]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Dia/Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "38d0e986-a291-4457-90c2-f3c61c7163df",
            "sourceColumn": "[Dia/Mes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "DiasSemana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b0056b34-a078-4c3c-a272-61257eda228b",
            "sourceColumn": "[DiasSemana]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Mes Atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "062d4b48-617c-4617-8e79-adc8a78425fe",
            "sourceColumn": "[Mes Atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano-Mes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "4c43272e-eeea-4570-bacd-db5a92688129",
            "sortByColumn": "OrderBy",
            "sourceColumn": "[Ano-Mes]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "OrderBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "6379e873-55cf-4831-8c85-75dc301562b1",
            "sourceColumn": "[OrderBy]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Numerosemana",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7095497f-4c70-4041-acf6-538c6f3ae07f",
            "sourceColumn": "[Numerosemana]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano Atual",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e359d342-a055-49aa-9776-99d5729ecaf7",
            "sourceColumn": "[Ano Atual]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SemanaDiaNome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2ae6d849-7446-4efd-bd3c-439cccf1b359",
            "sortByColumn": "SemanaDIAnum",
            "sourceColumn": "[SemanaDiaNome]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "SemanaDIAnum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "c76e7ca4-ae1a-4261-8bbd-65061bdc9f07",
            "sourceColumn": "[SemanaDIAnum]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "c1129b92-d7c3-44cf-ad21-17626ffd5317",
        "measures": [
          {
            "name": "TOTAL_DIAS",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT('CALENDARIO DAX'[Date]),",
              "    'Calendario DAX'[Mês] = MONTH(SELECTEDVALUE('Atualização'[data atualizada])) &&",
              "    'Calendario DAX'[Ano] = YEAR(SELECTEDVALUE('Atualização'[data atualizada]))",
              "    )"
            ],
            "lineageTag": "da5ce4fa-8846-40bb-9144-017ddce24f5a"
          },
          {
            "name": "DIAS_PERCORRIDOS",
            "expression": [
              "",
              "CALCULATE(",
              "    [TOTAL_DIAS],",
              "    'CALENDARIO DAX'[Date] <= SELECTEDVALUE('Atualização'[data atualizada])",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "c7a40e26-f7ad-4529-b9d4-6210dbc5f9b3"
          },
          {
            "name": "Dias Faltantes",
            "expression": [
              "",
              "VAR vDIAS =",
              "[TOTAL_DIAS] - [DIAS_PERCORRIDOS]",
              "RETURN",
              "\"Faltam: \" & FORMAT( vDIAS, \"\" ) & \" Dias Úteis\""
            ],
            "lineageTag": "9e91b074-c3aa-4bef-9c8c-41fa7b1c1913"
          }
        ],
        "partitions": [
          {
            "name": "CALENDARIO DAX",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "var minAno = YEAR(MIN(TB_NotaFiscal[NTF_DataEmissao])) //2021",
                "var MaxAno = YEAR(MAX(TB_NotaFiscal[NTF_DataEmissao])) //2026",
                "RETURN",
                "ADDCOLUMNS(",
                "    FILTER(",
                "        CALENDARAUTO(),",
                "        YEAR([Date]) >= minAno &&",
                "        YEAR([Date]) <= MaxAno),",
                "        \"Ano\", YEAR([Date]),",
                "        \"AnoNumber\", YEAR( [Date] ),",
                "        \"Mês\", MONTH([Date]),",
                "        \"Nome do Mês\", FORMAT([Date],\"mmmm\",\"PT-BR\"),",
                "        \"Mês Abrev\",UPPER(LEFT(FORMAT([Date], \"mmm\"), 1)) & LOWER(RIGHT(FORMAT([Date], \"mmm\"), 2)),",
                "        \"trimestre\", CONCATENATE(QUARTER([Date]),\"-Trimestre\"),",
                "        \"semestre\", SWITCH(",
                "                        TRUE(),",
                "                        MONTH([Date]) IN{1,2,3,4,5,6}, \"1-Sem\",",
                "                        \"2-Sem\"),",
                "        \"Dia\",DAY([Date]),",
                "        \"Dia/Mes\", FORMAT([Date],\"dd-mmm\") ,",
                "        \"SemanaDIAnum\", WEEKDAY( [Date], 1 ),",
                "        \"DiasSemana\",SWITCH(",
                "            WEEKDAY([Date]),",
                "            1,\"Domingo\",",
                "            2,\"Segunda\",",
                "            3,\"Terça\",",
                "            4,\"Quarta\",",
                "            5,\"Quinta\",",
                "            6,\"Sexta\",",
                "            7,\"Sabado\"),",
                "        \"SemanaDiaNome\", FORMAT( [Date] , \"ddd\"),",
                "        \"Mes Atual\", IF( YEAR( [Date] ) = YEAR( TODAY() ) && MONTH( [Date] ) = MONTH( TODAY() ), \"S\", \"N\" ),",
                "        \"Ano Atual\", IF( YEAR( [Date] ) = YEAR( TODAY() ) , \"S\", \"N\" ),",
                "        \"Ano-Mes\", UPPER(LEFT(FORMAT([Date], \"mmm\"), 1)) & LOWER(RIGHT(FORMAT([Date], \"mmm\"), 2)) & \"-\" & YEAR( [Date] ),",
                "        \"OrderBy\", (YEAR( [Date] )*100) + MONTH( [Date] ),",
                "        \"Numerosemana\", WEEKNUM( [Date])",
                "    )"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "TB_Cliente",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CLI_Codigo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6ee07ff2-a6dd-4948-b8d8-2b4ee727966b",
            "sourceColumn": "CLI_Codigo",
            "summarizeBy": "none"
          },
          {
            "name": "CLI_PES_IdPessoa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9b9b298c-affa-4265-8d27-9ff453193df6",
            "sourceColumn": "CLI_PES_IdPessoa",
            "summarizeBy": "sum"
          },
          {
            "name": "CLI_EMP_IdEmpresa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ffe207f0-19a3-4e80-a21d-717a2a8a44dd",
            "sourceColumn": "CLI_EMP_IdEmpresa",
            "summarizeBy": "none"
          },
          {
            "name": "CLI_Observacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b3922ff-c900-4f16-a41e-d4b33b0a4196",
            "sourceColumn": "CLI_Observacao",
            "summarizeBy": "none"
          },
          {
            "name": "CLI_PorcentagemDescontoVenda",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "acd5ffad-4fbb-453d-9b0a-4b921100225e",
            "sourceColumn": "CLI_PorcentagemDescontoVenda",
            "summarizeBy": "sum"
          },
          {
            "name": "CLI_LimiteCredito",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "598413f0-8b99-4b83-8a6e-b8b645c4ae1f",
            "sourceColumn": "CLI_LimiteCredito",
            "summarizeBy": "sum"
          },
          {
            "name": "CLI_TAB_IdTabelaPreco",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "267ec38c-c7f7-47e5-821b-5886735b1e28",
            "sourceColumn": "CLI_TAB_IdTabelaPreco",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7e40f7f1-75f4-49a1-93a5-bc77d3db3b55",
        "partitions": [
          {
            "name": "TB_Cliente",
            "mode": "import",
            "queryGroup": "TB_Dimensao",
            "source": {
              "expression": [
                "let",
                "    Fonte = PowerPlatform.Dataflows(null),",
                "    Workspaces = Fonte{[Id=\"Workspaces\"]}[Data],",
                "    #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\" = Workspaces{[workspaceId=\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"]}[Data],",
                "    #\"bda523c5-15d7-4d7e-890a-25ae41b17802\" = #\"6b3d0be9-cdbd-4454-b8dc-62bf05ebb307\"{[dataflowId=\"bda523c5-15d7-4d7e-890a-25ae41b17802\"]}[Data],",
                "    TB_Cliente_ = #\"bda523c5-15d7-4d7e-890a-25ae41b17802\"{[entity=\"TB_Cliente\",version=\"\"]}[Data]",
                "in",
                "    TB_Cliente_"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_ba8ade30-deee-4575-a7a3-2aa3845c20e8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "416dbc59-fbb7-40f8-9fb0-9de6a5eb7533",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eeb868bd-21da-4380-be56-05f5ce578203",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "35888cc1-4573-44cb-bf85-9d3a8f9076c6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3e15004a-c673-4095-a7e6-f63ddb49d450",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2b577dac-4daf-432f-9fe6-01c90df38c01",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "569de351-498c-4bad-8042-3a76d551ed86",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "bbcc5926-6049-45cd-923f-d0066822eedd",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "014cc615-d6f3-4703-b27c-e2bc58664af8",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "9b94f985-2206-4ef4-a4f7-fe89fed80971",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "9653e6f0-1cd8-4bd5-b096-74f5837edaf8",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "5df1f003-cd79-4565-8112-37c5f7813056",
                "ordinal": 3
              }
            ],
            "lineageTag": "ed7a96b6-6d43-4128-adf6-92bcd72b9aa1"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "dad2810b-047c-46fd-b0ac-bf456dfa4789",
        "partitions": [
          {
            "name": "DateTableTemplate_ba8ade30-deee-4575-a7a3-2aa3845c20e8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Atualização",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "data atualizada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "c9b88349-0a91-482a-bfb0-d77b682243cb",
            "sourceColumn": "data atualizada",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_c04fdd3a-08b1-4ddd-9343-ae9b9ec29a13"
                },
                "isDefault": true,
                "relationship": "40309711-f238-4c85-92df-3003ed3eb0a6"
              }
            ]
          }
        ],
        "lineageTag": "dacbe26d-b311-4a55-8a72-aed744de875a",
        "partitions": [
          {
            "name": "Atualização",
            "mode": "import",
            "queryGroup": "TB_Dimensao",
            "source": {
              "expression": [
                "let",
                "    Fonte = DateTimeZone.SwitchZone(DateTimeZone.LocalNow(),-3),",
                "    #\"Convertido para Tabela\" = #table(1, {{Fonte}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Convertido para Tabela\",{{\"Column1\", \"data atualizada\"}}),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"data atualizada\", type datetimezone}})",
                "in",
                "    #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c04fdd3a-08b1-4ddd-9343-ae9b9ec29a13",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4958ca4b-1dbd-49bb-829f-1e35bbfbfc46",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "81d419bd-5a37-42cd-8295-9d45b95d328d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "17dc695f-c93f-46c5-b47c-736a9ff4d43c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bc0cf6ad-ca38-4360-9fbf-7710d6754e42",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "53db9567-1f57-4090-883b-ef3e8ab33bc3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "a902e9b3-a391-4be3-b4c9-741d051e1219",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2f1b129c-4425-4485-8b4f-e0287f35196b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "6178fa87-741b-4add-bf73-fbd1b406d74e",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "f1fb7e76-264c-4660-9cf2-362d2420973a",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "03820e19-892d-4439-b211-f590d444e8e1",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "6ff4a599-b23b-46a3-89ba-d1ba4520669a",
                "ordinal": 3
              }
            ],
            "lineageTag": "064317e0-0283-4ee5-8174-5d0fa33ae204"
          }
        ],
        "isHidden": true,
        "lineageTag": "75fd1895-b3ef-4e53-810d-f5bc385fc273",
        "partitions": [
          {
            "name": "LocalDateTable_c04fdd3a-08b1-4ddd-9343-ae9b9ec29a13",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Atualização'[data atualizada])), 1, 1), Date(Year(MAX('Atualização'[data atualizada])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_2ca12eb1-9712-4962-a2da-3915b11f5664",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "501772e3-885c-434f-9865-add1601b76f0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "d3dffc24-e3b4-4655-87e8-7425deb36579",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4042bc7c-2cda-4a93-8c64-081c1c4565e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "690e60d6-b4f5-4524-9bdb-c9ece00fae2b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "eef8b0d2-0a32-4948-a46b-eb635691d47d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bfd419eb-0d33-4aec-90fd-179793478add",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a37664af-d51b-4e51-83e4-2ca5a636361b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ba944493-2da0-4264-8e90-4243477d8217",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "7c446779-b300-43cb-8040-c3c37d3ef9f6",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "6936d0d9-ff8c-41c5-bdcf-6e7cfdc338b9",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "70797177-4ccf-4677-9f10-07961c462c8b",
                "ordinal": 3
              }
            ],
            "lineageTag": "45547198-5f37-4d61-81b8-85819b10d9e8"
          }
        ],
        "isHidden": true,
        "lineageTag": "2afdf477-bfb8-4c9d-9953-ef2daffbbb90",
        "partitions": [
          {
            "name": "LocalDateTable_2ca12eb1-9712-4962-a2da-3915b11f5664",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('CALENDARIO DAX'[Date])), 1, 1), Date(Year(MAX('CALENDARIO DAX'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "xSenha",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "a04eb733c545493798efe99241f6ed5e"
          }
        ],
        "columns": [
          {
            "name": "xSenha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "5739180d-30c4-4b10-9bc2-af0b4e737c40",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6a6f104f-a6e7-42e2-a9ab-8c3ef30e0f7e",
        "measures": [
          {
            "name": "Valor xSenha",
            "expression": "SELECTEDVALUE('xSenha'[xSenha], 0)",
            "formatString": "0",
            "lineageTag": "9d8d78ad-68c0-4a65-aca9-0fe5fd689742"
          }
        ],
        "partitions": [
          {
            "name": "xSenha",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(1, 9999, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "_Senhas",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "acesso",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e98a3f1-64b8-4198-9972-7078095a6780",
            "sourceColumn": "acesso",
            "summarizeBy": "none"
          },
          {
            "name": "Senha",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "12d1efd3-13af-45c4-b448-92ec1f236156",
            "sourceColumn": "Senha",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "9e7740af-df83-45f6-9e17-f64b4d9cef82",
        "measures": [
          {
            "name": "AcessoButton",
            "expression": [
              "",
              "// Destinado ao Botão de Acesso",
              "SWITCH(",
              "    TRUE(),",
              "    HASONEFILTER( _Senhas[acesso] ) && xSenha[Valor xSenha] = MAX( _Senhas[Senha] ), \"HOME\", ",
              "    \"Senha Incorreta\" )"
            ],
            "lineageTag": "ff822c70-4070-4660-8f6c-fce412a32d18"
          }
        ],
        "partitions": [
          {
            "name": "_Senhas",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Excel.Workbook(Web.Contents(\"https://docs.google.com/spreadsheets/d/e/2PACX-1vQPEuaT2YmsawvEr8QTDHmxX1dK37pb1Vw543ubfV_kITWromJxKBI6bapNKp1TIw/pub?output=xlsx\"), null, true),",
                "    Plan1_Sheet = Fonte{[Item=\"Plan1\",Kind=\"Sheet\"]}[Data],",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Plan1_Sheet, [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"acesso\", type text}, {\"Senha\", Int64.Type}}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Tipo Alterado\", each [acesso] <> null and [acesso] <> \"\")",
                "in",
                "    #\"Linhas Filtradas\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}